### ISSUE TITLE
AppsecKit 3.4.0 does not work with Vaadin 24.9

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/appsec-kit#214]
I have a simple Spring-Boot project with Vaadin 24.9.0 and having vulnerabilities in the project the appsec kit notification throw an error in my browser console.

```
Uncaught (in promise) TypeError: e.addTab is not a function
    at Object.init (appsec-kit-plugin.js:52:7)
    at h.initPlugin (vaadin-dev-tools.js:795:3994)
    at Object.push (vaadin-dev-tools.js:795:3907)
    at appsec-kit-plugin.js:55:31
```

```
appsec-kit-plugin.js:25 Uncaught (in promise) TypeError: l.showNotification is not a function
    at t.handleMessage (appsec-kit-plugin.js:25:94)
    at Uo (copilot-Clqe7NnV.js:5272:27)
    at Hc (copilot-Clqe7NnV.js:5278:9)
    at HTMLElement.updated (copilot-Clqe7NnV.js:6077:60)
    at HTMLElement._$AE (copilot-Clqe7NnV.js:4336:121)
    at HTMLElement.performUpdate (copilot-Clqe7NnV.js:4331:15)
    at HTMLElement.scheduleUpdate (copilot-Clqe7NnV.js:4309:17)
    at HTMLElement._$EP (copilot-Clqe7NnV.js:4305:20)
```

in the log I see the following exceptions:
```
2025-09-27T15:30:46.731+02:00  INFO 11324 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2025-09-27T15:30:46.764+02:00  WARN 11324 --- [nio-8080-exec-1] c.v.f.s.c.PushAtmosphereHandler          : AtmosphereHandler.onRequest called before PushHandler has been set. This should really not happen
2025-09-27T15:30:47.161+02:00  INFO 11324 --- [           main] c.v.f.s.DefaultDeploymentConfiguration   : 
Vaadin is running in DEVELOPMENT mode - do not use for production deployments.
2025-09-27T15:30:47.216+02:00  INFO 11324 --- [           main] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
2025-09-27T15:30:47.486+02:00 ERROR 11324 --- [nio-8080-exec-5] org.atmosphere.cpr.AtmosphereFramework   : AtmosphereFramework exception

java.lang.IllegalStateException: Can not process requests before init() has been called
	at com.vaadin.flow.server.VaadinService.requestStart(VaadinService.java:1759) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:271) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:627) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77) ~[flow-server-24.9.0.jar:24.9.0]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:213) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:254) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:131) ~[tomcat-embed-websocket-10.1.44.jar:10.1.44]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:945) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1769) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1189) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:658) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-27T15:30:47.488+02:00  WARN 11324 --- [nio-8080-exec-5] o.a.websocket.DefaultWebSocketProcessor  : Failed invoking AtmosphereFramework.doCometSupport()

java.lang.IllegalStateException: Can not process requests before init() has been called
	at com.vaadin.flow.server.VaadinService.requestStart(VaadinService.java:1759) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:271) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:627) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103) ~[flow-server-24.9.0.jar:24.9.0]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77) ~[flow-server-24.9.0.jar:24.9.0]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:213) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:254) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:131) ~[tomcat-embed-websocket-10.1.44.jar:10.1.44]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:945) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1769) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1189) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:658) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.44.jar:10.1.44]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-27T15:30:47.489+02:00  WARN 11324 --- [nio-8080-exec-5] o.a.w.protocol.SimpleHttpProtocol        : java.lang.IllegalStateException: Can not process requests before init() has been called. Unable to deliver the websocket messages to installed component. Status 500 Message Server Error
2025-09-27T15:30:47.490+02:00  INFO 11324 --- [           main] c.v.a.service.AppSecServiceInitListener  : AppSec Kit initialized
2025-09-27T15:30:47.513+02:00  INFO 11324 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2025-09-27T15:30:47.519+02:00  INFO 11324 --- [           main] org.vaadin.demo.Application              : Started Application in 8.827 seconds (process running for 9.715)
2025-09-27T15:30:47.768+02:00  INFO 11324 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : Starting Vite
```

**Comment by tamasmak** [comment]
Fixed in AppSec Kit [3.4.1](https://github.com/vaadin/appsec-kit/releases/tag/3.4.1).
